### PR TITLE
Oxyde2

### PR DESCRIPTION
**Pull request by Oxyde2**
This pull request should solve issue #3 .
**Requesting Review**

* **XPath** queries can now be passed using the `-x` or `--xpath` flags. The program will only look through the specified nodes/elements of the HTML DOM when detecting changes.
* Added a new requirement though, [lxml](https://lxml.de/)

Hope this is what you needed! 😄 
-Oxyde

### CODE REVIEW

**Comment by n1try** [comment]
Thanks for your contribution and your research time you put into it! However, this is not quite working the way I wanted, yet.

Consider the following, very simple document.

```html
<html>
  <body>
    <p class="c1">Hello</p>
    <p class="c2">World</p>
  </body>
</html>
```
The goal is to be able to specify a query like `//p[@class="c1"]` to get notified about changes inside the first `<p>` tag only, while, for instance, changes in the second one are ignored.

In your code, `getNodes()` returns a list of XML nodes in the HTML document, 11 in this case. Those 11 include the `<html>`, the `<body>`, each of the `<p>` as well as all classes and all line breaks (`\n`). 
Previously, the script was comparing the number of characters in two versions of a document (90 characters in this case). Now, you are comparing the amount of XML nodes in two document (11 in this case), which are unlikely to change ever. Say, in the above document, `Hello` would change to `Goodbye`. The user would never notified, because the number of XML nodes, which you are comparing, remains 11.

What you rather would want to do is use the XPath query to filter out a certain part of the document (only the string `Goodbye` (`Hello`) for the above query example) and compare its amount of characters (7) with the older one (5).

- [ ] Please fix that :slightly_smiling_face: 

In addition to that, I have a few further "style"-related remarks, which might be a bit picky, but also easy to change.

- [ ] Please remove the `watcher_cache.txt` file from Git again.
- [ ] Also, please change it back to be stored in a temporary directory. If you are on windows, where there is no `/tmp`, you could even add the ability to use a platform-independent temp dir using [tempfile](https://stackoverflow.com/a/847866/3112139) module.
- [ ] The [information hiding](https://en.wikipedia.org/wiki/Information_hiding) principle suggests that a method should not receive any more information than it necessarily needs. Though it's not critical at all in this case, you still might want to stick to the principle and only pass `args.xpath` to `getNodes()`, instead of the entire `args` list.
- [ ] Please stick to the Python way of snake-case method names (e.g. `get_nodes()` instead of `getNodes()` (I know, this is picky, but it makes the code look much more beautiful if everything is consistent :wink:).

**Comment by n1try** [comment]
Another hint to help you further: instead (or in addition to) `get_nodes()`, you would probably want to have a function like `filter_document()` that takes an XPath query (or a list of nodes as returned by `get_nodes()` as an input and returns a string, which corresponds to the part of the document that is of interest according to the query. Good luck! :wink:

**Comment by Oxyde2** [comment]
Ok then.
### Fixes :hammer_and_wrench:
* The `get_nodes( )` function still returns lxml nodes according to the XPath query.
* The `filter_document( )` function returns a string containing the all the text contained in the specified nodes (Even the newlines and tabs, should this be removed?).
* The `len1` and `len2` variables should now containing the number of characters in the *"search area"* or part of the document to sift through.
* Used [tempfile](https://docs.python.org/3/library/tempfile.html) to have multi-platform temp folder support. :tada:

### Let's turn to *"style"* :art: now:
* Added docstrings to the `get_nodes( )` and `filter_document( )` functions :bulb:
* Removed `watcher_cache.txt` file from Git :fire:
* Implemented the [imformation hiding principle](https://en.wikipedia.org/wiki/Information_hiding) for the functions. :information_source:
* Used more *pythonic* function names. :snake:

Awaiting your review.
-Oxyde

**Comment by n1try** [comment]
Very cool! Almost ready to be merged.
Only two more very minor things:

- [ ] Please fix the typo in `filter_documemt()`
- [ ] Please make `//body` the default value for `--xpath`, instead of `//*`

Thanks!

**Comment by Oxyde2** [comment]
Sure thing!

**Comment by Oxyde2** [comment]
However I don't see any typo in the `filter_document` function.
I'm sorry, my eyes must be tired... 😪

**Comment by n1try** [comment]
It was `documemt` instead of `document`. But don't worry, I fixed it.

**Comment by Oxyde2** [comment]
OK thanks!

**Comment by Oxyde2** [comment]
If you need anything else I'm here to help :smile:

**Pull request merged**
